/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'tableNumber' : bigint,
  'placedAt' : bigint,
  'items' : Array<OrderItem>,
  'estimatedMinutes' : [] | [bigint],
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : number,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'ready' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearTableOrders' : ActorMethod<[bigint], undefined>,
  'confirmOrder' : ActorMethod<[bigint, bigint], undefined>,
  'createMenuItem' : ActorMethod<
    [string, string, number, string, string],
    bigint
  >,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getActiveKitchenOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getOrderStatus' : ActorMethod<[bigint], OrderStatus>,
  'getTableBill' : ActorMethod<[bigint], number>,
  'getTableOrders' : ActorMethod<[bigint], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderReady' : ActorMethod<[bigint], undefined>,
  'payBill' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[bigint, Array<OrderItem>], bigint>,
  'toggleMenuItemAvailability' : ActorMethod<[bigint], undefined>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, number, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];