/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'ready' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'tableNumber' : IDL.Nat,
  'placedAt' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
  'estimatedMinutes' : IDL.Opt(IDL.Nat),
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearTableOrders' : IDL.Func([IDL.Nat], [], []),
  'confirmOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getActiveKitchenOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [OrderStatus], ['query']),
  'getTableBill' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getTableOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderReady' : IDL.Func([IDL.Nat], [], []),
  'payBill' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [IDL.Nat], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'tableNumber' : IDL.Nat,
    'placedAt' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
    'estimatedMinutes' : IDL.Opt(IDL.Nat),
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearTableOrders' : IDL.Func([IDL.Nat], [], []),
    'confirmOrder' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getActiveKitchenOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [OrderStatus], ['query']),
    'getTableBill' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getTableOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderReady' : IDL.Func([IDL.Nat], [], []),
    'payBill' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [IDL.Nat], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [], []),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };